#include"STD_TYPES.h"
#include"BIT_MATH.h"

#include"DIO_INTERFACE.h"
#include"LED_INTERFACE.h"
#include"SW_INTERFACE.h"
#include"EXTI_INTERFACE.h"
#include"GIE_INTERFACE.h"


	LED_TYPE L1={LED_PIN0,LED_PORTA,ACTIVE_HIGH};
	LED_TYPE L2={LED_PIN1,LED_PORTA,ACTIVE_HIGH};
	SW_TYPE S1={DIO_PORTD,DIO_PIN2,SW_INT_PULL_UP};
	SW_TYPE S2={DIO_PORTD,DIO_PIN3,SW_INT_PULL_UP};

	void S1_FUNC(){
		LED_TOGGLE(L1);


	}
	void S2_FUNC(){
		LED_TOGGLE(L2);


	}

void main(){

	LED_INIT(L1);
	LED_INIT(L2);
	SW_INIT(S1);
	SW_INIT(S2);
	EXTI_SET_SIGNAL_LATCH(EXTI_FALLING_EDGE,EXTI_LINE0);
	EXTI_SET_SIGNAL_LATCH(EXTI_FALLING_EDGE,EXTI_LINE1);
	EXTI_SET_CALL_BACK(S1_FUNC,0);
	EXTI_SET_CALL_BACK(S2_FUNC,1);
	EXTI_ENABLE_INTRUPT(EXTI_LINE0);
	EXTI_ENABLE_INTRUPT(EXTI_LINE1);
    GIE_ENABLE();
    while(1);

}
